
/// Member
module.exports = {
    START_MONEY: 5000, //// START MONEY

    WORK_MONEY_MIN: 50, //// WORK MONEY
    WORK_MONEY_MAX: 200, //// WORK MONEY
    WORK_COOLDOWN: 0,
    WORK_COOLDOWN_TIME: 20, //// WORK COOLDOWN TIME

    CRIME_MONEY_MIN: 1500, //// CRIME MONEY
    CRIME_MONEY_MAX: 3000, //// CRIME MONEY
    CRIME_COOLDOWN: 0, 
    CRIME_COOLDOWN_TIME: 120, //// CRIME COOLDOWN TIME 
    CRIME_CHANCE: 40, //// CRIME CHANCE 40 = 40%

    ROB_COOLDOWN: 0,
    ROB_COOLDOWN_TIME: 3600, //// RUB COOLDOWN TIME
    ROB_CHANCE: 50, //// ROB CHANCE 50 = 50%

    ROULETTE_START: 100, //// MONEY TO START ROULETTE

    VOTE_COOLDOWN: 0,
    VOTE_COOLDOWN_TIME: 3600, //// VOTE COOLDOWN TIME
}